spring.application.name=cursoFullStack
server.port=8081
# H2 Console - Spring Boot 4
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Opcional pero recomendado
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true